stages:
  - build
  - test
  - analysis
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "true"

build:make:
  stage: build
  script:
    - mkdir -p build
    - make -j$(nproc)
  artifacts:
    when: on_success
    paths: 
      - ./build/* 
    expire_in: 5 mins

test:run:
  stage: test
  dependencies:
    - build:make
  script:
    - cd ./build
    - ./release/c4 --tokenize ../example/hello_world.c
    - ./release/c4 --parse ../example/hello_world.c

build:test:
  stage: build
  script:
    - mkdir -p build
    - cd ./build
    - cmake ..
    - make -j$(nproc)
    - cd ..
  artifacts:
    when: on_success
    paths: 
      - ./build/* 
    expire_in: 5 mins

test:entry:
  stage: test
  dependencies:
    - build:test
  script:
    - cd ./build
    - ./test_entry

test:lexer:
  stage: test
  dependencies:
    - build:test
  script:
    - cd ./build
    - ./test_lexer

test:parser:
  stage: test
  dependencies:
    - build:test
  script:
    - cd ./build
    - ./test_parser

analysis:coverage:
  stage: analysis
  script:
    - mkdir -p build
    - cd ./build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE_TESTING=ON ..
    - make -j$(nproc)
    - ./test_entry
    - ./test_lexer
    - ./test_parser
    - cd ..
    - chmod +x ./scripts/coverage.sh
    - ./scripts/coverage.sh
  artifacts:
    when: on_success
    paths: 
      - ./coverage/*
    expire_in: 5 mins

deploy:benchmark:
  stage: deploy
  script:
    - echo "The cake is a lie."
  only:
    refs:
      - master
      - develop
  artifacts:
    paths: 
      - ./benchmark.svg
    expire_in: 1 week

