stages:
  - llvm
  - build
  - run
  - test
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "true"

ccc:llvm:
  stage: llvm
  script:
    - ls
    - bash build_llvm.sh
    - ls llvm/install/bin/
    - export PATH="$PATH:$PWD/llvm/install/bin/"
    - clang++ --version
    - llc --version
    - lli --version
    - opt --version
  cache:
    key: one-key-to-rule-them-all
    paths:
    - llvm/install/

ccc:build:
  stage: build
  dependencies:
    - ccc:llvm
  script:
    - mkdir -p build/
    - make -j$(nproc)
  cache:
    key: one-key-to-rule-them-all
    paths:
      - llvm/install/
  artifacts:
    when: on_success
    paths:
      - build/
    expire_in: 10 mins

ccc:run:
  stage: run
  dependencies:
    - ccc:build
  script:
    - cd build/
    - ./release/c4 --tokenize ../examples/sample.c
    - ./release/c4 --parse ../examples/sample.c
    - ./release/c4 --print-ast ../examples/sample.c
    - ./release/c4 --graphviz ../examples/sample.c
  cache:
    key: one-key-to-rule-them-all

ccc:test:
  stage: test
  dependencies:
    - ccc:build
  script:
    - cd build/
    - cmake ..
    - make check -j$(nproc)
  cache:
    key: one-key-to-rule-them-all
    paths:
      - llvm/install/
  allow_failure: true

ccc:deploy:
  stage: deploy
  script:
    - echo "The cake is a lie."
  only:
    refs:
      - master
  artifacts:
    paths:
      - benchmark.svg
    expire_in: 3 days
  allow_failure: true
